### ISSUE TITLE
Occured java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled

### ISSUE THREAD

**Issue by takat0-h0rikosh1** [akka/akka-grpc#1144]
Hi. I tried to write client program. When I let my app to run, I saw some error logging.

```
*** (i.g.n.s.i.n.u.i.l.InternalLoggerFactory) Using SLF4J as the default logging framework
*** (i.g.n.s.i.n.u.i.PlatformDependent) Platform: MacOS
*** (i.g.n.s.i.n.u.i.PlatformDependent0) -Dio.netty.noUnsafe: false
*** (i.g.n.s.i.n.u.i.PlatformDependent0) Java version: 14
*** (i.g.n.s.i.n.u.i.PlatformDependent0) sun.misc.Unsafe.theUnsafe: available
*** (i.g.n.s.i.n.u.i.PlatformDependent0) sun.misc.Unsafe.copyMemory: available
*** (i.g.n.s.i.n.u.i.PlatformDependent0) java.nio.Buffer.address: available
*** (i.g.n.s.i.n.u.i.PlatformDependent0) direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.grpc.netty.shaded.io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:225)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:219)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:72)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:74)
	at akka.grpc.internal.NettyClientUtils$.createChannel(NettyClientUtils.scala:41)
	at akka.grpc.internal.ClientState.<init>(ClientState.scala:30)

...

*** (i.g.n.s.i.n.u.i.PlatformDependent0) java.nio.Bits.unaligned: available, true
*** (i.g.n.s.i.n.u.i.PlatformDependent0) jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @3a51abf
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:647)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:335)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:326)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:72)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:74)
	at akka.grpc.internal.NettyClientUtils$.createChannel(NettyClientUtils.scala:41)
	at akka.grpc.internal.ClientState.<init>(ClientState.scala:30)

...

*** (i.g.n.s.i.n.u.i.PlatformDependent0) java.nio.DirectByteBuffer.<init>(long, int): unavailable
*** (i.g.n.s.i.n.u.i.PlatformDependent) sun.misc.Unsafe: available
*** (i.g.n.s.i.n.u.i.PlatformDependent) maxDirectMemory: 1073741824 bytes (maybe)
*** (i.g.n.s.i.n.u.i.PlatformDependent) -Dio.netty.tmpdir: /var/folders/ny/skt3twln2131ksckvh2z49j4qv6b8g/T (java.io.tmpdir)
*** (i.g.n.s.i.n.u.i.PlatformDependent) -Dio.netty.bitMode: 64 (sun.arch.data.model)
*** (i.g.n.s.i.n.u.i.PlatformDependent) -Dio.netty.maxDirectMemory: -1 bytes
*** (i.g.n.s.i.n.u.i.PlatformDependent) -Dio.netty.uninitializedArrayAllocationThreshold: -1
*** (i.g.n.s.i.n.u.i.CleanerJava9) java.nio.ByteBuffer.cleaner(): available
*** (i.g.n.s.i.n.u.i.PlatformDependent) -Dio.netty.noPreferDirect: false
*** (i.g.n.s.i.n.u.i.NativeLibraryLoader) -Dio.netty.native.workdir: /var/folders/ny/skt3twln2131ksckvh2z49j4qv6b8g/T (io.netty.tmpdir)
*** (i.g.n.s.i.n.u.i.NativeLibraryLoader) -Dio.netty.native.deleteLibAfterLoading: true
*** (i.g.n.s.i.n.u.i.NativeLibraryLoader) -Dio.netty.native.tryPatchShadedId: true
*** (i.g.n.s.i.n.u.i.NativeLibraryLoader) Unable to load the library 'io_grpc_netty_shaded_netty_tcnative_osx_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative_osx_x86_64 in java.library.path: [/Users/t_horikoshi/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2680)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1907)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:581)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:133)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:217)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:414)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:513)
	at akka.grpc.internal.NettyClientUtils$.createChannel(NettyClientUtils.scala:93)
	at akka.grpc.internal.ClientState.<init>(ClientState.scala:30)

...

*** (i.g.n.s.i.n.u.i.NativeLibraryLoader) io_grpc_netty_shaded_netty_tcnative_osx_x86_64 cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /var/folders/ny/skt3twln2131ksckvh2z49j4qv6b8g/T
java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative_osx_x86_64 in java.library.path: [/Users/t_horikoshi/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2680)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1907)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:581)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:133)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:217)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:414)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:513)
	at akka.grpc.internal.NettyClientUtils$.createChannel(NettyClientUtils.scala:93)
	at akka.grpc.internal.ClientState.<init>(ClientState.scala:30)

        ...

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at sbt.Run.invokeMain(Run.scala:115)
	at sbt.Run.execute$1(Run.scala:79)
	at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.base/java.lang.Thread.run(Thread.java:832)
	Suppressed: java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative_osx_x86_64 in java.library.path: [/Users/t_horikoshi/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2680)
		at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
		at java.base/java.lang.System.loadLibrary(System.java:1907)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
		... 44 common frames omitted
```

Let shared part of program.

##### application.conf

```
akka.grpc.client {
  "my-program" {
    host = "localhost"
    port = 50051
  }
}
```

##### client program

```
val conf = ConfigFactory
  .load()
  .withFallback(ConfigFactory.defaultApplication())
val system = ActorSystem("my-program", conf)
val clientSettings = GrpcClientSettings.fromConfig(clientName = "my-program")(system)
val client = MyServiceClient(clientSettings)(system)
```

##### java version

```
$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```

is this java version wrong???
https://stackoverflow.com/questions/60241857/java-lang-unsupportedoperationexception-reflective-setaccessibletrue-disabled

Why does the error logging occured？
Could you tell me way of to stop error logging.

Thank you.

**Comment by takat0-h0rikosh1** [comment]
Is this logging waring log by netty？
https://github.com/netty/netty/issues/7817

The issue will close if I know way to change log level for netty.

**Comment by dumpsterfireproject** [comment]
I was getting the same exception with my application running on adoptopenjdk 11.0.8, akka 2.6.10, akka-http 10.2.1, and sbt-akka-grpc 1.0.2.  I added `<logger name="io.grpc.netty.shaded.io" level="OFF"/>` to my logback.xml and it stopped the exception.

**Comment by takat0-h0rikosh1** [comment]
@dumpsterfireproject Thanks for your sharing. It was success to stop warning logging from netty.
