### ISSUE TITLE
[failed] NonBalancingIntegrationSpecAkkaHttp

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-grpc#1327]
Failed in (travis) https://travis-ci.com/github/akka/akka-grpc/jobs/498878703#L6648

```
[info] NonBalancingIntegrationSpecAkkaHttp:
[info] Using pick-first (non load balanced clients)
[info] - should send requests to a single endpoint (541 milliseconds)
[info] - should send requests to a single endpoint that is restarted in the middle (458 milliseconds)
[info] - should re-discover endpoints on failure (5 seconds, 61 milliseconds)
[info] - should select the right endpoint among invalid ones *** FAILED *** (15 seconds, 37 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Waited 15000000000 nanoseconds. (NonBalancingIntegrationSpec.scala:153)
[info]   org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:339)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.grpc.scaladsl.NonBalancingIntegrationSpec.$anonfun$new$11(NonBalancingIntegrationSpec.scala:153)
[info]   at akka.grpc.scaladsl.NonBalancingIntegrationSpec.$anonfun$new$11$adapted(NonBalancingIntegrationSpec.scala:152)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:190)
[info]   at akka.grpc.scaladsl.NonBalancingIntegrationSpec.$anonfun$new$10(NonBalancingIntegrationSpec.scala:152)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
...
```

**Comment by ignasi35** [comment]
This happens very often when running the build on GHActions (https://github.com/akka/akka-grpc/pull/1325)

**Comment by ignasi35** [comment]
But it happens sometimes on Travis too: https://travis-ci.com/github/akka/akka-grpc/jobs/498878703

**Comment by ignasi35** [comment]
Happened again in https://github.com/akka/akka-grpc/pull/1434/checks?check_run_id=3418060213 :-(
