### ISSUE TITLE
Failed: ServerReflectionImplSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-grpc#1759]
https://github.com/akka/akka-grpc/actions/runs/4415745436/jobs/7739114465#step:5:305

That is one tight timeout ...

```
[info] - should retrieve server reflection info *** FAILED *** (212 milliseconds)
[305](https://github.com/akka/akka-grpc/actions/runs/4415745436/jobs/7739114465#step:5:306)
[info]   A timeout occurred waiting for a future to complete. Waited 150 milliseconds. (ServerReflectionImplSpec.scala:57)
[306](https://github.com/akka/akka-grpc/actions/runs/4415745436/jobs/7739114465#step:5:307)
[info]   org.scalatest.concurrent.ScalaFutures$$anon$2:
[307](https://github.com/akka/akka-grpc/actions/runs/4415745436/jobs/7739114465#step:5:308)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:345)
[308](https://github.com/akka/akka-grpc/actions/runs/4415745436/jobs/7739114465#step:5:309)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[309](https://github.com/akka/akka-grpc/actions/runs/4415745436/jobs/7739114465#step:5:310)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:259)
[310](https://github.com/akka/akka-grpc/actions/runs/4415745436/jobs/7739114465#step:5:311)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[311](https://github.com/akka/akka-grpc/actions/runs/4415745436/jobs/7739114465#step:5:312)
[info]   at akka.grpc.internal.ServerReflectionImplSpec.f$proxy3$1(ServerReflectionImplSpec.scala:57)
[312](https://github.com/akka/akka-grpc/actions/runs/4415745436/jobs/7739114465#step:5:313)
[info]   at akka.grpc.internal.ServerReflectionImplSpec.$init$$$anonfun$2$$anonfun$1(ServerReflectionImplSpec.scala:63)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/4738830299/jobs/8413084560#step:5:404

**Comment by octonato** [comment]
https://github.com/akka/akka-grpc/actions/runs/4792964505/jobs/8524980210#step:5:440

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/5855366397/job/15873035593?pr=1819#step:5:361

**Comment by patriknw** [comment]
https://github.com/akka/akka-grpc/actions/runs/22746934604/job/65972636348#step:6:513
