### ISSUE TITLE
failed: GrpcInteropAkkaJavaWithIoSpec - should pass the server_compressed_unary integration test

### ISSUE THREAD

**Issue by octonato** [akka/akka-grpc#1813]
https://github.com/akka/akka-grpc/actions/runs/5503370952/jobs/10028503048#step:5:5763

```scala
[5762](https://github.com/akka/akka-grpc/actions/runs/5503370952/jobs/10028503048#step:5:5763)
[info] - should pass the server_compressed_unary integration test *** FAILED *** (168 milliseconds)
[info]   org.scalatest.exceptions.TestFailedException was thrown. (GrpcInteropTests.scala:88)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
[info]   at org.scalatest.wordspec.AnyWordSpec.newAssertionFailedException(AnyWordSpec.scala:1879)
[info]   at org.scalatest.Assertions.fail(Assertions.scala:965)
[info]   at org.scalatest.Assertions.fail$(Assertions.scala:961)
[info]   at org.scalatest.wordspec.AnyWordSpec.fail(AnyWordSpec.scala:1879)
[info]   at akka.grpc.interop.GrpcInteropTests.withGrpcServer(GrpcInteropTests.scala:88)
[info]   at akka.grpc.interop.GrpcInteropTests.$anonfun$new$4(GrpcInteropTests.scala:50)
[info]   at akka.grpc.interop.GrpcInteropTests.pendingTestCaseSupport(GrpcInteropTests.scala:97)
[info]   at akka.grpc.interop.GrpcInteropTests.$anonfun$new$3(GrpcInteropTests.scala:50)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1227)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at org.scalatest.wordspec.AnyWordSpec.withFixture(AnyWordSpec.scala:1879)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1225)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1237)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1237)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1219)
[info]   at org.scalatest.wordspec.AnyWordSpec.runTest(AnyWordSpec.scala:1879)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1296)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/5933601029/job/16089235450#step:5:5716

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/15432182590/job/43431903199#step:5:4903

Logged error
```
Caused by: org.junit.AssumptionViolatedException: 66825048 is not sufficient to run this test
	at org.junit.Assume.assumeTrue(Assume.java:68)
	at io.grpc.testing.integration.AbstractInteropTest.assumeEnoughMemory(AbstractInteropTest.java:1765)
	at io.grpc.testing.integration.AbstractInteropTest.serverCompressedUnary(AbstractInteropTest.java:515)
	at io.grpc.testing.integration2.GrpcJavaClientTester.serverCompressedUnary(GrpcJavaClientTester.java:53
```

**Comment by patriknw** [comment]
https://github.com/akka/akka-grpc/actions/runs/18149405862/job/51657128446#step:5:4828

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/21463783259/job/61821466684#step:5:5122

**Comment by johanandren** [comment]
https://github.com/akka/akka-grpc/actions/runs/23327097228/job/67850440666#step:6:5132
