### ISSUE TITLE
NullPointerException in akka.grpc.internal.GrpcMetadataImpl.asList

### ISSUE THREAD

**Issue by jtjeferreira** [akka/akka-grpc#1854]
### Versions used 

Akka version: 2.8.5
Akka-http: 10.5.2
Akka-grpc version: 2.3.4
scala: 2.13.11

### Actual Behavior

I updated akka-grpc from 2.1.6. to 2.3.4 and I see a `NullPointerException` as shown in the below stack trace. The application is a grpc service (let's call it service A) that calls downstream service (let's call it service B). From the stack trace below one can see this is happening near the `GrpcExceptionHandler` (i.e when an exception is being converted to a grpc response). From what I collected from other telemetry sources this is only happening when service B returns an error (i.e grpc status code != Ok).

### Expected Behavior

No `NullPointerException` should be thrown 

### Relevant logs

```
Error during processing of request: 'java.lang.NullPointerException (No error message supplied)'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
at akka.grpc.internal.GrpcMetadataImpl.asList(MetadataImpl.scala:106)
at akka.grpc.internal.GrpcEntityHelpers$.metadataHeaders(GrpcEntityHelpers.scala:74)
at akka.grpc.internal.GrpcEntityHelpers$.trailer(GrpcEntityHelpers.scala:67)
at akka.grpc.internal.GrpcResponseHelpers$.status(GrpcResponseHelpers.scala:101)
at akka.grpc.scaladsl.GrpcExceptionHandler$.$anonfun$from$1(GrpcExceptionHandler.scala:58)
at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:289)
at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:269)
at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
at scala.concurrent.impl.Promise$Transformation.run$$original(Promise.scala:490)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:141)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:64)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:101)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:101)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
at com.lightbend.akka.RecordingRunnable.run(RecordingRunnable.scala:24)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

### Reproducible Test Case

I don't have a reproducible test case

### Investigation

I think the NPE is due to `delegate` in `class GrpcMetadataImpl(delegate: io.grpc.Metadata)` being null. I can reproduce this in a REPL like this:
```scala
akka.grpc.internal.GrpcResponseHelpers.status(akka.grpc.Trailers(io.grpc.Status.INTERNAL, new akka.grpc.internal.RichGrpcMetadataImpl(io.grpc.Status.INTERNAL, null)))
java.lang.NullPointerException
  at akka.grpc.internal.GrpcMetadataImpl.asList(MetadataImpl.scala:106)
  at akka.grpc.internal.GrpcEntityHelpers$.metadataHeaders(GrpcEntityHelpers.scala:74)
  at akka.grpc.internal.GrpcEntityHelpers$.trailer(GrpcEntityHelpers.scala:67)
  at akka.grpc.internal.GrpcResponseHelpers$.status(GrpcResponseHelpers.scala:101)
  ... 59 elided
```

I think the problem is that in #1665 a translation of `StatusRuntimeException` to `GrpcServiceException` was [introduced](https://github.com/akka/akka-grpc/pull/1665/files#diff-f520c3fa84a37ea4f85a575bd972473557eda3a8c5ce1b78cfd06e30c58be7a5R402-R409), that uses `akka.grpc.GrpcServiceException#apply(ex: StatusRuntimeException) method` which does `new GrpcServiceException(ex.getStatus, new RichGrpcMetadataImpl(ex.getStatus, ex.getTrailers))` and does not handle the case that `ex.getTrailers` can be null.

### Workaround

I am testing at the moment if handling the `GrpcServiceException` in a custom handler like below fixes the issue:
```scala
    case grpcException: GrpcServiceException =>
      val meta = Option(grpcException.getTrailers).getOrElse(new io.grpc.Metadata())
      Trailers(grpcException.status, new GrpcMetadataImpl(meta))
```

**Comment by johanandren** [comment]
Thanks for the detailed report. 

I agree, it seems like  `GprcServiceException#apply` is the culprit.

**Comment by jtjeferreira** [comment]
The workaround described above fixed the problem...
