### ISSUE TITLE
NullPointerException in TLS client

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#299]
When running 'sbt scripted' on jenkins. 

Possibly https://bugs.java.com/view_bug.do?bug_id=8049855? the jdk on jenkins is at 1.8.0_45.

```
[info] Using fake CA for TLS certificate. Test clients should expect host
[info] *.test.google.fr and our test CA. For the Java test client binary, use:
[info] --server_host_override=foo.test.google.fr --use_test_ca=true
[error] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[error] SLF4J: Defaulting to no-operation (NOP) logger implementation
[error] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Running test large_unary
[info] Exception: io.grpc.StatusRuntimeException: UNKNOWN
[info] Server stopped
[error] io.grpc.StatusRuntimeException: UNKNOWN
[error] 	at io.grpc.Status.asRuntimeException(Status.java:526)
[error] 	at akka.grpc.internal.UnaryCallAdapter.onClose(UnaryCallAdapter.scala:43)
[error] 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
[error] 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
[error] 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
[error] 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
[error] 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
[error] 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
[error] 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
[error] 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
[error] 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
[error] 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
[error] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
[error] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
[error] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
[error] 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[error] 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Caused by: io.grpc.netty.shaded.io.netty.handler.codec.DecoderException: java.lang.NullPointerException
[error] 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[error] 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[error] 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[error] 	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[error] 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[error] 	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[error] 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[error] 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
[error] 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[error] 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[error] 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[error] 	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[error] 	... 1 more
[error] Caused by: java.lang.NullPointerException
[error] 	at java.lang.System.arraycopy(Native Method)
[error] 	at com.sun.crypto.provider.GCTR.reset(GCTR.java:125)
[error] 	at com.sun.crypto.provider.GCTR.doFinal(GCTR.java:116)
[error] 	at com.sun.crypto.provider.GaloisCounterMode.doLastBlock(GaloisCounterMode.java:343)
[error] 	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:511)
[error] 	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1023)
[error] 	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:960)
[error] 	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:479)
[error] 	at javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:830)
[error] 	at javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
[error] 	at javax.crypto.Cipher.doFinal(Cipher.java:2460)
[error] 	at sun.security.ssl.CipherBox.decrypt(CipherBox.java:535)
[error] 	at sun.security.ssl.EngineInputRecord.decrypt(EngineInputRecord.java:200)
[error] 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:974)
[error] 	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
[error] 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
[error] 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
[error] 	at io.grpc.netty.shaded.io.netty.handler.ssl.JdkSslEngine.unwrap(JdkSslEngine.java:90)
[error] 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:294)
[error] 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1275)
[error] 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177)
[error] 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221)
[error] 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[error] 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[error] 	... 16 more
[error] org.scalatest.exceptions.TestFailedException: UNKNOWN
[error] 	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
[error] 	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
[error] 	at org.scalatest.WordSpec.newAssertionFailedException(WordSpec.scala:1881)
[error] 	at org.scalatest.Assertions.fail(Assertions.scala:1105)
[error] 	at org.scalatest.Assertions.fail$(Assertions.scala:1101)
[error] 	at org.scalatest.WordSpec.fail(WordSpec.scala:1881)
[error] 	at com.lightbend.grpc.interop.GrpcInteropTests.withGrpcServer(GrpcInteropTests.scala:83)
[error] 	at com.lightbend.grpc.interop.GrpcInteropTests.$anonfun$grpcTests$4(GrpcInteropTests.scala:52)
[error] 	at com.lightbend.grpc.interop.GrpcInteropTests$$Lambda$175/1587362577.apply$mcV$sp(Unknown Source)
[error] 	at com.lightbend.grpc.interop.GrpcInteropTests.pendingTestCaseSupport(GrpcInteropTests.scala:100)
[error] 	at com.lightbend.grpc.interop.GrpcInteropTests.$anonfun$grpcTests$3(GrpcInteropTests.scala:52)
[error] 	at com.lightbend.grpc.interop.GrpcInteropTests$$Lambda$85/48581062.apply(Unknown Source)
[error] 	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[error] 	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[error] 	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:22)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:20)
[error] 	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[error] 	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[error] 	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[error] 	at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[error] 	at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
[error] 	at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
[error] 	at org.scalatest.WordSpecLike$$Lambda$163/1892068254.apply(Unknown Source)
[error] 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[error] 	at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
[error] 	at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
[error] 	at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[error] 	at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
[error] 	at org.scalatest.WordSpecLike$$Lambda$144/936081845.apply(Unknown Source)
[error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[error] 	at org.scalatest.SuperEngine$$Lambda$145/669560071.apply(Unknown Source)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
[error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
[error] 	at org.scalatest.SuperEngine$$Lambda$145/669560071.apply(Unknown Source)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[error] 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[error] 	at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1147)
[error] 	at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1146)
[error] 	at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[error] 	at org.scalatest.Suite.run(Suite.scala:1147)
[error] 	at org.scalatest.Suite.run$(Suite.scala:1129)
[error] 	at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[error] 	at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1192)
[error] 	at org.scalatest.WordSpecLike$$Lambda$137/1121280693.apply(Unknown Source)
[error] 	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[error] 	at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1192)
[error] 	at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1190)
[error] 	at org.scalatest.WordSpec.run(WordSpec.scala:1881)
[error] 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:301)
[error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:291)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Caused by: io.grpc.netty.shaded.io.netty.handler.codec.DecoderException: java.lang.NullPointerException
[error] 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[error] 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[error] 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[error] 	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[error] 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[error] 	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[error] 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[error] 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
[error] 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[error] 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[error] 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[error] 	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[error] 	... 1 more
[error] Caused by: java.lang.NullPointerException
[error] 	at java.lang.System.arraycopy(Native Method)
[error] 	at com.sun.crypto.provider.GCTR.reset(GCTR.java:125)
[error] 	at com.sun.crypto.provider.GCTR.doFinal(GCTR.java:116)
[error] 	at com.sun.crypto.provider.GaloisCounterMode.doLastBlock(GaloisCounterMode.java:343)
[error] 	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:511)
[error] 	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1023)
[error] 	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:960)
[error] 	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:479)
[error] 	at javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:830)
[error] 	at javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
[error] 	at javax.crypto.Cipher.doFinal(Cipher.java:2460)
[error] 	at sun.security.ssl.CipherBox.decrypt(CipherBox.java:535)
[error] 	at sun.security.ssl.EngineInputRecord.decrypt(EngineInputRecord.java:200)
[error] 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:974)
[error] 	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
[error] 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
[error] 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
[error] 	at io.grpc.netty.shaded.io.netty.handler.ssl.JdkSslEngine.unwrap(JdkSslEngine.java:90)
[error] 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:294)
[error] 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1275)
[error] 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177)
[error] 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221)
[error] 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[error] 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[error] 	... 16 more
```

**Comment by raboof** [comment]
JDK update (to 1..0_171) indeed appears to have done the trick
