### ISSUE TITLE
Streams kills each other

### ISSUE THREAD

**Issue by peteremiljensen** [akka/akka-grpc#357]
Hi again.

If I open multiple streams at the same time using a shared client and next closes the first stream using KillSwitch, then the other streams fails. However, the first stream finishes with success.

I get the following error on the failing streams:

```
io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: PROTOCOL_ERROR
Received Goaway
Received unexpected frame of type RstStreamFrame for stream 13 in state Closed
  at io.grpc.Status.asRuntimeException(Status.java:526)
  at akka.grpc.internal.AkkaNettyGrpcClientGraphStage$$anon$1.onCallClosed(AkkaNettyGrpcClientGraphStage.scala:170)
  at akka.grpc.internal.AkkaNettyGrpcClientGraphStage$$anon$1.$anonfun$callback$1(AkkaNettyGrpcClientGraphStage.scala:74)
  at akka.grpc.internal.AkkaNettyGrpcClientGraphStage$$anon$1.$anonfun$callback$1$adapted(AkkaNettyGrpcClientGraphStage.scala:70)
  at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:454)
  at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
  at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
  at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
  at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
  at akka.actor.Actor.aroundReceive(Actor.scala:517)
  at akka.actor.Actor.aroundReceive$(Actor.scala:515)
  at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
  at akka.actor.ActorCell.invoke(ActorCell.scala:557)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
  at akka.dispatch.Mailbox.run(Mailbox.scala:225)
  at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
  at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by peteremiljensen** [comment]
The server gives the following error:
```
[ERROR] [08/21/2018 12:50:38.105] [db-akka.actor.default-dispatcher-7] [akka://db/system/StreamSupervisor-0/flow-15-0-detacher] Error in stage [akka.http.impl.engine.http2.Http2ServerDemux@714184ff]: requirement failed
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:264)
	at akka.http.impl.engine.http2.Http2MultiplexerSupport$$anon$1$WithSendableOutStreams.sendNext(Http2Multiplexer.scala:301)
	at akka.http.impl.engine.http2.Http2MultiplexerSupport$$anon$1$WaitingForNetworkToSendData.onPull(Http2Multiplexer.scala:315)
	at akka.http.impl.engine.http2.Http2MultiplexerSupport$$anon$1.onPull(Http2Multiplexer.scala:225)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:526)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:422)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by peteremiljensen** [comment]
Here is a reproducer for project `akka-grpc-plugin-tester-scala`:

```
import example.myapp._

import scala.concurrent.ExecutionContext
import scala.concurrent.Future
import akka.actor.ActorSystem
import akka.grpc.scaladsl.ServiceHandler
import akka.http.scaladsl.Http
import akka.http.scaladsl.HttpsConnectionContext
import akka.http.scaladsl.model.StatusCodes
import akka.http.scaladsl.model.HttpRequest
import akka.http.scaladsl.model.HttpResponse
import akka.stream.ActorMaterializer
import akka.stream.Materializer
import com.typesafe.config.ConfigFactory

import example.myapp.helloworld._
import example.myapp.helloworld.grpc._

import example.myapp.echo._
import example.myapp.echo.grpc._

import akka.http.scaladsl._
import akka.grpc._

import akka.grpc.scaladsl.ServiceHandler

val conf = ConfigFactory.parseString("akka.http.server.preview.enable-http2 = on")
.withFallback(ConfigFactory.defaultApplication())
implicit val sys: ActorSystem = ActorSystem("HelloWorld", conf)
implicit val mat: Materializer = ActorMaterializer()
implicit val ec: ExecutionContext = sys.dispatcher

val greeterService: PartialFunction[HttpRequest, Future[HttpResponse]] =
  example.myapp.helloworld.grpc.GreeterServiceHandler.partial(new GreeterServiceImpl(mat))

Http().bindAndHandleAsync(
  greeterService,
  interface = "127.0.0.1",
  port = 8080,
  parallelism = 256,
  connectionContext = HttpConnectionContext(UseHttp2.Always)
)
.foreach { binding =>


  println(s"gRPC server bound to: ${binding.localAddress}")

  val client = GreeterServiceClient(GrpcClientSettings.connectToServiceAt("localhost", 8080).withTls(false))

  // Long enough to make sure we dont finish too early
  val text = (0 to 1000).map(_ => "test").mkString

  // Here we craete two streams, where the second kills the first

  lazy val first = client.itKeepsReplying(HelloRequest(text))
    .viaMat(akka.stream.KillSwitches.single)(akka.stream.scaladsl.Keep.right)
    .toMat(akka.stream.scaladsl.Sink.ignore)(akka.stream.scaladsl.Keep.both)
    .run
  lazy val kill = first._1.shutdown
  lazy val second = client.itKeepsReplying(HelloRequest(text))
    .viaMat(akka.stream.KillSwitches.single)(akka.stream.scaladsl.Keep.right)
    .map{ x => kill; x } 
    .toMat(akka.stream.scaladsl.Sink.ignore)(akka.stream.scaladsl.Keep.both)
    .run

  first._2.onComplete(x => println(s"first: $x"))
  second._2.onComplete(x => println(s"second: $x"))
}
```

**Comment by TimMoore** [comment]
I wonder if it is related to #285/#348, which is fixed but not yet released. Does this reproduce with a `SNAPSHOT` build from `master`?

**Comment by raboof** [comment]
He is setting `parallelism = 256`, which AFAICS should work around #348

**Comment by peteremiljensen** [comment]
The problem still persists with the latest commit as of the time of writing

**Comment by peteremiljensen** [comment]
Is there any news on this? :)

**Comment by johanandren** [comment]
Here's actually an even simpler repeater, that fails the same way most of the time:
```
       val first = client.itKeepsReplying(HelloRequest("first" + text))
        .runWith(Sink.head)
      val second = client.itKeepsReplying(HelloRequest("second" + text))
        .runWith(Sink.ignore)

      first.onComplete(x => println(s"first: $x"))
      second.onComplete(x => println(s"second: $x"))
```

**Comment by johanandren** [comment]
[failure.log](https://github.com/akka/akka-grpc/files/2433879/failure.log)

Here's the debug log for a run when it failed.

**Comment by johanandren** [comment]
Enabling the Netty client logs makes the error go away but there are some pretty fishy errors in those logs as well, the client seems to do a lot of resetting, and then logs an error for data on a streamid it says it doesn't recognise: 
[netty.log.gz](https://github.com/akka/akka-grpc/files/2434231/netty.log.gz)

**Comment by peteremiljensen** [comment]
Is this waiting for akka-http 10.1.6 release?

**Comment by raboof** [comment]
@peteremiljensen correct

**Comment by peteremiljensen** [comment]
Does there exist an estimated time? :)

**Comment by johanandren** [comment]
Yes, the fix has been merged so it will be in Akka HTTP 10.1.6, next release probably in the next couple of weeks (no promises though).

**Comment by peteremiljensen** [comment]
I understand :) Thanks

**Comment by peteremiljensen** [comment]
Hey guys. I can see that 10.1.6 has been released. Really nice. When does this get resolved then? :)

**Comment by peteremiljensen** [comment]
The error seems to still occur

**Comment by peteremiljensen** [comment]
Can you confirm that the problem still persists?

**Comment by johanandren** [comment]
Tried the reproducer on Akka HTTP 10.1.6 and 10.1.7, the error is different but it still fails:

```
first: Success(HelloReply(H))
second: Failure(io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: PROTOCOL_ERROR
Received Goaway
Received unexpected frame of type RstStreamFrame for stream 3 in state Closed)
```

Complete failure log at debug:
[failure.txt](https://github.com/akka/akka-grpc/files/2755224/failure.txt)

**Comment by peteremiljensen** [comment]
Can I expect this to be resolved?

**Comment by raboof** [comment]
I had a closer look. Wireshark is an amazing tool here: when disabling TLS, it can fairly clearly show what is going on in terms of HTTP/2 frames.

I identified an issue in Akka HTTP and created a patch at https://github.com/akka/akka-http/pull/2457 that at least appears to fix the small reproducer @johanandren showed above.

@peteremiljensen could you see if this also resolves the problem in your case?

**Comment by peteremiljensen** [comment]
YESS! It seems to fix the problem 🥇 Thank you

**Comment by raboof** [comment]
Great, thanks for testing! (and of course for the original report ;) )

**Comment by raboof** [comment]
(fixed upstream)
