### ISSUE TITLE
Play Java clients should 500 on an empty gRPC request 

### ISSUE THREAD

**Issue by dwijnand** [akka/akka-grpc#396]
In #391 when creating [PlayJavaFunctionalTest](https://github.com/akka/akka-grpc/blob/9dc5475783183d91c214f6ea581e23444a7a5079/play-testkit/src/test/java/akka/grpc/play/test/PlayJavaFunctionalTest.java), based on [PlayScalaTestSpec](https://github.com/akka/akka-grpc/blob/9dc5475783183d91c214f6ea581e23444a7a5079/play-testkit/src/test/scala/akka/grpc/scalatestplus/play/PlayScalaTestSpec.scala) and [PlaySpecs2Spec](https://github.com/akka/akka-grpc/blob/9dc5475783183d91c214f6ea581e23444a7a5079/play-testkit/src/test/scala/akka/grpc/play/api/specs2/PlaySpecs2Spec.scala), I discovered that where in Scala a Play server bound to a gRPC router gives a 500 when routing an empty request to a gRPC method, in Java it gives a 200!

For now I resolved it by [`@Ignore`ing the test method](https://github.com/akka/akka-grpc/blob/9dc5475783183d91c214f6ea581e23444a7a5079/play-testkit/src/test/java/akka/grpc/play/test/PlayJavaFunctionalTest.java#L78-L81).

**Comment by dwijnand** [comment]
The ScalaTest and specs2 tests show:

```scala
[] ERROR akka.actor.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:504)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

while the Java one shows:

```
java.util.NoSuchElementException: head of empty stream
```

But more interestingly it looks like just the Java test boots up io.grpc.netty:

```
DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - Successfully loaded the library /var/folders/jy/jgttnxcd4750bdcw119bc9cw0000gn/T/libio_grpc_netty_shaded_netty_tcnative_osx_x86_64.dylib
```

**Comment by raboof** [comment]
Also, perhaps we should think whether we expect a `4xx` error in this case?

**Comment by dwijnand** [comment]
Maybe 🙂. Rich mentioned 426.

**Comment by dwijnand** [comment]
The io.grpc.netty bootup turned out to be a red herring on how that test started a gRPC client (which uses netty) while the scala tests weren't.

Still stuck on the difference.

**Comment by dwijnand** [comment]
Sounds reasonable to me.

**Comment by ignasi35** [comment]
After reviewing in more detail I don't thinks this is a huge issue. The tests as they are written exercise gRPC endpoints using regular HTTP clients (even using `HTTP/1.1`) which is a programming error.

It's be great if the Java counterpart returned `500` (consistently with the scala impl) though.

With this in mind, I understand what Rich meant with `// Maybe should be a 426`: because the client is not `HTTP/2` the server should detect the inconsistency and request a [`426 Upgrade Required`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426). Actually I think `426` would be correct in those cases where Rich left a comment.


- - - - - 

PS: my [comment](https://github.com/akka/akka-grpc/issues/396#issuecomment-421382387) above doesn't make sense because the test is actually reproducing what I consider a programming error (using a non-gRPC client to exercise a gRPC endpoint).

**Comment by raboof** [comment]
Given https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses, a 200 response with the error in a trailing grpc-status header might also be acceptable. It'd be good if the scala and java API behavior is consistent, though ;).
