### ISSUE TITLE
Adding a JVM parameter to application.conf file causes errors

### ISSUE THREAD

**Issue by saurabhsharma721** [akka/akka-grpc#769]
### Versions used 

Akka version:  "2.5.25"

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

In Scala grpc quickstart if we add any new property in application.conf which reads values from Jvm parameters, the application crashes in config reading.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

In Scala quick start project add following lines in application.conf

testproject {
    log-level = "INFO"
    log-level = ${?LOG_LEVEL}
}

This log-level is supposed to command line parameter set by our cloud formation project.

This causes the project to fail while starting up.

### Relevant logs

If you identified a section in your logs that explains the bug or might be important to understand it, please add it.

Exception in thread "main" com.typesafe.config.ConfigException$NotResolved: need to Config#resolve() each config before using it, see the API docs for Config#resolve()
	at com.typesafe.config.impl.SimpleConfig.checkValid(SimpleConfig.java:1103)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:322)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:703)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:258)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:302)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:276)
	at com.example.helloworld.GreeterServer$.main(GreeterServer.scala:26)
	at com.example.helloworld.GreeterServer.main(GreeterServer.scala)

### Reproducible Test Case

Please provide a PR with a failing test.

If the issue is more complex or requires configuration, please provide a link to a project that reproduces the issue.

**Comment by raboof** [comment]
Thank you for your report! I had a quick look, and the problem is where it says `.withFallback(ConfigFactory.defaultApplication())` this should be `.withFallback(ConfigFactory.load())`.

Would you be interested in testing if this fixes the problem for you, and perhaps even providing a PR to fix the quickstart project?
