### ISSUE TITLE
"head of empty stream" exception when sending response in akka-http route

### ISSUE THREAD

**Issue by jokester** [akka/akka-grpc#774]
### Versions used 

akka version: 2.6.1
akka-http version: 10.1.11
akka-grpc version: 0.7.3
rest: ArchLinux x64 / openjdk 11 / scala 2.13.1

### Steps to produce

1. clone the minimal example at https://github.com/jokester/experimental-akka-grpc (it contains a dummy grpc service implementation that returns `Future.failed`), and `sbt run`
2. in another terminal, run the following command:

```
curl 'http://localhost:9090/examplecom.library.BookService/GetBook' --compressed -H 'content-type: application/grpc-web+proto' -H 'x-grpc-web: 1' --data $'\x00\x00\x00\x00\x00' | wc
```

### Expected Behavior

- curl will read some bytes from chunked (I expected there to be at least 1 trailing chunk for `grpc-status`)
- akka throws no exception

### Actual Behavior

- curl gets 0 bytes
- the following exception thrown in akka

// the stream might be the one created in [GrpcResponseHelpers](https://github.com/akka/akka-grpc/blob/4bef58f0fe8f6bd91333b51722a4153be6021713/runtime/src/main/scala/akka/grpc/internal/GrpcResponseHelpers.scala#L64), but I was not able to go deeper

```
20:13:10.211 [main-system-akka.actor.default-dispatcher-9] ERROR akka.actor.ActorSystemImpl - head of empty stream
java.util.NoSuchElementException: head of empty stream
	at akka.stream.scaladsl.Sink$.$anonfun$head$3(Sink.scala:197)
	at scala.Option.getOrElse(Option.scala:201)
	at akka.stream.scaladsl.Sink$.$anonfun$head$2(Sink.scala:197)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:85)
	at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:122)
	at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:116)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:84)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at akka.stream.impl.HeadOptionStage$$anon$3.onUpstreamFinish(Sinks.scala:235)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:523)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:594)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:701)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:750)
	at akka.actor.Actor.aroundPreStart(Actor.scala:544)

```

**Comment by jokester** [comment]
I encountered this when trying to use akka-grpc itself as a grpc-web server. I'm aware this usage is not officially supported (see https://github.com/akka/akka-grpc/issues/695), but the exception looked like a unrelated bug to me.

**Comment by raboof** [comment]
Thanks for the great reproducer, that really helps!

This threw me for a while as well, but I think I got it now:

1) The exception is thrown because your `.proto` promises that `GetBook` will take a `GetBookRequest` parameter with an `isbn`, and I don't think `--data $'\x00\x00\x00\x00\x00'` provides that.
2) the chunk with trailing header is actually sent (in this case with `grpc-status: 13`, the INTERNAL error), but you have to pass `--raw -v` to `curl` to actually see it.

I think we could improve the behavior here though: not showing such a distracting stack trace in the logs and returning a `INVALID_ARGUMENT` status code.

**Comment by raboof** [comment]
Improved the error reporting
