### ISSUE TITLE
Log file can not be found for multiproject Gradle projects

### ISSUE THREAD

**Issue by orendain** [akka/akka-grpc#786]
### Versions used 

Akka version: 
akka-grpc-gradle-plugin:0.7.3

### Expected Behavior

When building a Gradle project with multiple subprojects (e.g., a root gradle build and at least one subproject build), building the project from the root project should work.

Specifically: `./gradlew build` from the root project's directory should complete successfully.

The same goes for if the project is built not from the root project, but from the specific subproject.

### Actual Behavior

If the build is triggered from the **_subproject_**, things work as expected for that subproject.

If the build is triggered from the **_root_**, the Gradle plugin complains that a log does not exist (see below for relevant logs).

This regression is due to a change made in PR #674, which addresses issue #669.

### Relevant logs

```
> Task :subProject:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':subProject:generateProto'.
> protoc: stdout: . stderr: /Users/eorendain/Documents/myProject/subProject/src/main/protobuf: warning: directory does not exist.
  /Users/eorendain/Documents/myProject/subProject/app/protobuf: warning: directory does not exist.
  /Users/eorendain/Documents/myProject/subProject/app/proto: warning: directory does not exist.
  bytestream.proto: warning: Import google/protobuf/wrappers.proto but not used.
  Exception in thread "main" java.io.FileNotFoundException: build/akka-grpc-gradle-plugin.log (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at java.base/java.io.PrintWriter.<init>(PrintWriter.java:208)
        at java.base/java.io.PrintWriter.<init>(PrintWriter.java:248)
        at akka.grpc.gen.FileLogger.<init>(Logging.scala:35)
        at akka.grpc.gen.Main$.$anonfun$logger$1(Main.scala:48)
        at scala.Option.map(Option.scala:230)
        at akka.grpc.gen.Main$.delayedEndpoint$akka$grpc$gen$Main$1(Main.scala:48)
        at akka.grpc.gen.Main$delayedInit$body.apply(Main.scala:14)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at akka.grpc.gen.Main$.main(Main.scala:14)
        at akka.grpc.gen.Main.main(Main.scala)
  --akkaGrpc_out: protoc-gen-akkaGrpc: Plugin failed with status code 1.
```

### Reproducible Test Case

Apologies, I don't have much time to whip up a test case, but one would be simple to create.  Simply create a multi-project Gradle build wherein a subproject uses this Akka gRPC Gradle plugin, and run the commands as outlined above.

### Fix

I'll submit a PR with a fix in a few moments for testing/feedback.

**Comment by hithran** [comment]
Could someone please provide me some insights?
Because I've been trying to figure out why the colon causes trouble, instead of trying to work around the issue the relative path causes as I do not see a solution. I;m unable to generate the correct path based on wherefrom the task is run. As the task generation is done on loading, and not when running the task.

So I've been tracking the handling of the path which brought me to the Main of akka-grpc-codegen. It receives a `com.google.protobuf.compiler.PluginProtos.CodeGeneratorRequest` on its input. 
When I output the contents of the bytearray, the colon is already gone. So I think the colon is mishandled either during the parsing of the Gradle config or when generating the CodeGeneratorRequest.
But I'm unable to figure out who or what is responsible for providing it on the stdin. Anyone have a pointer where to search next? Or suggestions on how to proceed?

**Comment by laurikimmel** [comment]
I'd recommend to make [`logFile` in `akkaGrpc`](https://github.com/akka/akka-grpc/blob/c7e7794aca5ab73df626ffa306456a0b9fd029ed/gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy#L107) user configurable.  In such case it would be possible to point log file to `$buildDir/akka-grpc-gradle-plugin.log`, `/dev/null`, etc.

**Comment by laurikimmel** [comment]
Maybe it is helpful to someone - I managed to get multi-module build working by following ugly hack. I updated sub module's `build.gradle` and added

```
printProtocLogs.doFirst {
    mkdir "$buildDir"
    file("$buildDir/akka-grpc-gradle-plugin.log").text = "x"
    mkdir "$project.rootDir/build"
    file("$project.rootDir/build/akka-grpc-gradle-plugin.log").text = "x"
}

printProtocLogs.configure {
    mkdir "$buildDir"
    file("$buildDir/akka-grpc-gradle-plugin.log").text = "x"
    mkdir "$project.rootDir/build"
    file("$project.rootDir/build/akka-grpc-gradle-plugin.log").text = "x"
}
```

**Comment by AndreyIlin** [comment]
Hi, today I've updated to the latest intellij idea 2021.1 
IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Akka grpc: `akka-grpc-gradle-plugin:1.0.2`

And proto generation started to fail either with 
`java.io.FileNotFoundException: {subprojectName}/build/protoc.log (No such file or directory)` in multiproject build or
`java.io.FileNotFoundException: build/akka-grpc-gradle-plugin.log (No such file or directory)` for  project where protofile lies in subporject but main project applies plugin.

This happens when I build with gradle toolbar in Intellij.
Works fine on a previous version of Intellij.
Also works fine if I build with ./gradlew in console.
Doesn't work even if I put build/akka-grpc-gradle-plugin.log

I also found this issue 
https://youtrack.jetbrains.com/issue/IDEA-265203 
But workaround with user.dir override doesn't work either for me.

I understand that IDE issues seems unrelated but maybe they've changed something related to gradle that breaks plugins and projects for a lot of programmers that use Intellij.

**Comment by kKdH** [comment]
Same problem here. Also a multi-project build.

````
protoc: stdout: . stderr: Exception in thread "main" java.io.FileNotFoundException: build/akka-grpc-gradle-plugin.log (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at java.base/java.io.PrintWriter.<init>(PrintWriter.java:208)
        at java.base/java.io.PrintWriter.<init>(PrintWriter.java:248)
        at akka.grpc.gen.FileLogger.<init>(Logging.scala:35)
        at akka.grpc.gen.Main$.$anonfun$logger$1(Main.scala:48)
        at scala.Option.map(Option.scala:230)
        at akka.grpc.gen.Main$.delayedEndpoint$akka$grpc$gen$Main$1(Main.scala:48)
        at akka.grpc.gen.Main$delayedInit$body.apply(Main.scala:14)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at akka.grpc.gen.Main$.main(Main.scala:14)
        at akka.grpc.gen.Main.main(Main.scala)
  --akkaGrpc_out: protoc-gen-akkaGrpc: Plugin failed with status code 1.
````

````
------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (Oracle Corporation 11.0.10+9)
OS:           Linux 5.8.0-50-generic amd64
````

This isn't an IDE issue. [Stefan Oehme wrote](https://youtrack.jetbrains.com/issue/IDEA-265203#focus=Comments-27-4830577.0-0)

> [...] Unfortunately, for historical reasons, Gradle sets its current working directory to the so-called "search directory", which is usually the directory you've started your build from. This means that in some cases, relative paths will kind of work. As a result, many of you have not noticed that your builds are using this pattern. [...]

> A long time ago, the JetBrains team added a really hacky workaround so that this also kind of works in IntelliJ. This workaround was breaking other stuff in the IDE though, so they had to finally remove it. [...]

So i think this has to be fixed in the akka-grpc gradle plugin by "using" relative paths correctly.
