### ISSUE TITLE
Try different discovered endpoints on failures

### ISSUE THREAD

**Issue by vasily-kirichenko** [akka/akka-grpc#804]
Is there a load balancing client example available anywhere?

What I've tried:

```scala
val config = ConfigFactory.parseString(
    s"""
       |akka {
       |  discovery {
       |    method = "config"
       |    config.services {
       |      service1 {
       |        endpoints = [
       |          { host = "localhost", port = 9444 } // no service listening on this address
       |          { host = "localhost", port = 9443 } // a service *is* listening on this one
       |        ]
       |      }
       |    }
       |  }
       |
       |  grpc.client {
       |    "${Service.name}" {
       |      service-discovery {
       |        mechanism = "config"
       |        service-name = "service1"
       |      }
       |      grpc-load-balancing = "round_robin"
       |    }
       |  }
       |}
       |""".stripMargin)

  implicit val actorSystem = ActorSystem("client", config.withFallback(ConfigFactory.load()))
  implicit val mat = ActorMaterializer()
  implicit val ec = actorSystem.dispatcher

  val client = ServiceClient(
    GrpcClientSettings
      .fromConfig(Service.name)
      .withTls(true)
      .withSSLContext(sslContext)
      .withDeadline(3.seconds))

  for (i <- 1 to 10) {
    val called = client.push(Request(i))

    called.onComplete {
      case Success(value) => log.info(s"$i) Got reply $value")
      case Failure(e) => log.error(s"$i) The call failed: ${e.getMessage}")
    }
  }
```
This results with:
```
15:11:05.624 [client-akka.actor.default-dispatcher-3] ERROR Main - The call failed
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at akka.grpc.internal.UnaryCallAdapter.onClose(UnaryCallAdapter.scala:40)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:9444
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:579)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:820)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

The interesting part is 

```
io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:9444
```

As I see it, the client picks one of the endpoints at creation time, then use it forever:
```
15:23:52.888 [client-akka.actor.default-dispatcher-6] ERROR Main - 6) The call failed: UNAVAILABLE: io exception
15:23:52.888 [client-akka.actor.default-dispatcher-6] ERROR Main - 10) The call failed: UNAVAILABLE: io exception
15:23:52.888 [client-akka.actor.default-dispatcher-6] ERROR Main - 1) The call failed: UNAVAILABLE: io exception
15:23:52.888 [client-akka.actor.default-dispatcher-6] ERROR Main - 8) The call failed: UNAVAILABLE: io exception
15:23:52.888 [client-akka.actor.default-dispatcher-6] ERROR Main - 7) The call failed: UNAVAILABLE: io exception
15:23:52.889 [client-akka.actor.default-dispatcher-4] ERROR Main - 3) The call failed: UNAVAILABLE: io exception
15:23:52.889 [client-akka.actor.default-dispatcher-4] ERROR Main - 4) The call failed: UNAVAILABLE: io exception
15:23:52.889 [client-akka.actor.default-dispatcher-4] ERROR Main - 9) The call failed: UNAVAILABLE: io exception
15:23:52.890 [client-akka.actor.default-dispatcher-3] ERROR Main - 5) The call failed: UNAVAILABLE: io exception
15:23:52.893 [client-akka.actor.default-dispatcher-6] ERROR Main - 2) The call failed: UNAVAILABLE: io exception
```
or, if it's lucky:
```
15:25:52.122 [client-akka.actor.default-dispatcher-3] INFO  Main - 4) Got reply Reply(5)
15:25:52.125 [client-akka.actor.default-dispatcher-3] INFO  Main - 2) Got reply Reply(3)
15:25:52.125 [client-akka.actor.default-dispatcher-3] INFO  Main - 8) Got reply Reply(9)
15:25:52.129 [client-akka.actor.default-dispatcher-3] INFO  Main - 3) Got reply Reply(4)
15:25:52.140 [client-akka.actor.default-dispatcher-3] INFO  Main - 9) Got reply Reply(10)
15:25:52.141 [client-akka.actor.default-dispatcher-3] INFO  Main - 5) Got reply Reply(6)
15:25:52.141 [client-akka.actor.default-dispatcher-3] INFO  Main - 1) Got reply Reply(2)
15:25:52.142 [client-akka.actor.default-dispatcher-3] INFO  Main - 7) Got reply Reply(8)
15:25:52.143 [client-akka.actor.default-dispatcher-3] INFO  Main - 10) Got reply Reply(11)
15:25:52.144 [client-akka.actor.default-dispatcher-3] INFO  Main - 6) Got reply Reply(7)
```

Is it expected behaviour? What I really need here is trying all endpoints silently, i.e. no exceptions unless *all* the endpoints are unavailable. No message lost. Is it possible?

**Comment by raboof** [comment]
@vasily-kirichenko thanks for the report! What version of akka-grpc are you running? I think 0.7.3 had some improvements in this area.

The intent definitely is that when the connection fails, we try to connecting again, possibly to other endpoints from the discovered list of endpoints, before actually failing requests passed to the client. The underlying implementation has various ways of signalling failures, though, so it is definitely possible we missed a scenario - in that case that would be interesting to look into.

**Comment by raboof** [comment]
Note that this issue is actually about retrying different nodes on failure, not necessarily load-balancing.

If you're interested in actual client-side load balancing, you might be interested to follow #811

**Comment by raboof** [comment]
This should work since #811
